### ISSUE TITLE
Points cluster around the origin(x=0)

### ISSUE THREAD

**Issue by zhongjingjogy** [pabristow/svg_plot#4]
Hi paul,

I am coming across a problem which seems to be related to std::map with double key. Maybe this might solve by create a struct with data series, `x` and `y`. 

![image](https://user-images.githubusercontent.com/9261231/43352033-907a822e-924f-11e8-850e-5cfe79d0a48c.png)

**Comment by pabristow** [comment]
Puzzling – we haven’t seen this behaviour in lots of plots.

I would not have chosen std::map for this program, but the original author did and it seems to work OK,
and has some benefits for other than x-y pairs.

It would also be helpful to use a different colour for each sim-daruil-n and exp-daruil-n?

and only plot one x-y set  sim-daruil-n.

I note that some values are outside the axis-ranges you have chosen – the cone/triangle pointing down shows this.

So set x_range to about -0.001 to -0.0001  and 0.0006,

and y-range to a little less than zero (I can’t see your y-axis range)  perhaps

Can you email me a subset of your data and the C++ program plot part and I’ll try to reproduce (and fix).

Paul

pbristow@hetp.u-net.com<mailto:pbristow@hetp.u-net.com>

**Comment by zhongjingjogy** [comment]
Sorry for this issue. I have made a stupid mistake in my code when I try to get values for the experimental data from an array by using the wrong index of those for the simulation results. I have manage to solve this on my own, and I would like post the figure here.

I think using float key is okay in case that we only want to plot with the values, because the key and the value would not be modified. 

![image](https://user-images.githubusercontent.com/9261231/43364786-bae0b218-9353-11e8-94f5-5d388e6b3cb4.png)

**Comment by pabristow** [comment]
Looks much prettier.

 

Any numerical type that is convertible to double should work OK.

 

(Aside: Jake Voytko, the original author who works on this as a Google Summer of Code project, and who now works for Google, is severely color blind.  This accounts for some of the curious-to-the-normally-sighted color schemes.) 

 

Enjoy.

 

Paul

 

PS I will try to give a little more space in the legend box so that the final character is not half outside the box.  I had not noticed this because I chose a white or faint background for everything.
